---
name: Secret Scan

on:
  pull_request:

permissions: read-all

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with shallow clone
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@7c0734f987ad0bb30ee8da210773b800ee2016d3 # v3.93.4
        with:
          extra_args: --results=verified,unknown
